## PMW3610 Driver
## https://github.com/badjeff/zmk-pmw3610-driver
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y

## https://github.com/badjeff/zmk-pmw3610-driver/blob/main/Kconfig
CONFIG_PMW3610_ALT_SWAP_XY=y
CONFIG_PMW3610_ALT_INVERT_X=y
CONFIG_PMW3610_ALT_INVERT_Y=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12
